// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MetaGameBase.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MetaGameBase {

  /// <summary>Holder for reflection information generated from MetaGameBase.proto</summary>
  public static partial class MetaGameBaseReflection {

    #region Descriptor
    /// <summary>File descriptor for MetaGameBase.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MetaGameBaseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJNZXRhR2FtZUJhc2UucHJvdG8SDE1ldGFHYW1lQmFzZSIVCgVIZWFydBIM",
            "CgR0aW1lGAEgASgDKhoKBnN0YXR1cxIICgRGQUlMEAASBgoCT0sQASq1AQoI",
            "UHJvdG9jb2wSCwoHVU5LTk9XThAAEg4KCkhFQVJUX0JFQVQQARIRCg1DMlNf",
            "TE9HSU5fUkVREAISEQoNUzJDX0xPR0lOX1JFUxADEhIKDkMyU19MT0dPVVRf",
            "UkVREAQSEgoOUzJDX0xPR09VVF9SRVMQBRIVChFDMlNfR0FNRV9EQVRBX1JF",
            "URAGEhQKEFMyQ19VU0VSX09QRVJBVEUQBxIRCg1TMkNfVVNFUl9MSVNUEAhC",
            "HwodY29tLm1ldGEubmV0dHkucHJvdG9idWYucHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MetaGameBase.status), typeof(global::MetaGameBase.Protocol), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MetaGameBase.Heart), global::MetaGameBase.Heart.Parser, new[]{ "Time" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum status {
    [pbr::OriginalName("FAIL")] Fail = 0,
    [pbr::OriginalName("OK")] Ok = 1,
  }

  /// <summary>
  /// 协议ID
  /// </summary>
  public enum Protocol {
    /// <summary>
    ///未知协议
    /// </summary>
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    /// <summary>
    /// 心跳
    /// </summary>
    [pbr::OriginalName("HEART_BEAT")] HeartBeat = 1,
    /// <summary>
    ///用户登陆请求
    /// </summary>
    [pbr::OriginalName("C2S_LOGIN_REQ")] C2SLoginReq = 2,
    /// <summary>
    ///用户登陆响应
    /// </summary>
    [pbr::OriginalName("S2C_LOGIN_RES")] S2CLoginRes = 3,
    /// <summary>
    ///退出请求
    /// </summary>
    [pbr::OriginalName("C2S_LOGOUT_REQ")] C2SLogoutReq = 4,
    /// <summary>
    ///退出响应
    /// </summary>
    [pbr::OriginalName("S2C_LOGOUT_RES")] S2CLogoutRes = 5,
    /// <summary>
    ///游戏数据
    /// </summary>
    [pbr::OriginalName("C2S_GAME_DATA_REQ")] C2SGameDataReq = 6,
    /// <summary>
    ///用户登陆退出通知
    /// </summary>
    [pbr::OriginalName("S2C_USER_OPERATE")] S2CUserOperate = 7,
    /// <summary>
    ///用户列表
    /// </summary>
    [pbr::OriginalName("S2C_USER_LIST")] S2CUserList = 8,
  }

  #endregion

  #region Messages
  /// <summary>
  ///*
  ///心跳 时间
  ///HEART_BEAT
  /// </summary>
  public sealed partial class Heart : pb::IMessage<Heart> {
    private static readonly pb::MessageParser<Heart> _parser = new pb::MessageParser<Heart>(() => new Heart());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Heart> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MetaGameBase.MetaGameBaseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heart() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heart(Heart other) : this() {
      time_ = other.time_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Heart Clone() {
      return new Heart(this);
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 1;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Heart);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Heart other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Time != other.Time) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Time != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Time);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Heart other) {
      if (other == null) {
        return;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Time = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
